__include__:
  - base.yaml

environment:
  project: "tspn_fewshot_just"
  output_dir: "results/tspn_fewshot_just"
  notes: "JUST system 18, domain-focused adaptation."

data:
  batch_size: 48

task:
  target_system_id: [18]
  target_domain_id: [2, 4, 6, 8]
  source_domain_id: [1, 3, 5, 7, 9]
  lr: 0.002
  epochs: 100
  type: "DG"

trainer:
  num_epochs: 100
  patience: 10
