__include__:
  - base.yaml

environment:
  project: "tspn_fewshot_sdust"
  output_dir: "results/tspn_fewshot_sdust"
  notes: "SDUST system adaptation."

model:
  num_classes: 10
  in_channels: 6

task:
  target_system_id: [21]
  target_domain_id: [40]
  source_domain_id: [3, 7, 12, 16, 20, 24]
  epochs: 120
  lr: 0.0025
  type: "DG"

trainer:
  num_epochs: 120
  patience: 12
